// GUMPIDS.INC
//
// Creator: Myrathi <tjh@myrathi.co.uk>
// Created: 25-Apr-2001

// Game Boards
//--
const GID_CHESS		:= 0x91A;
const GID_BACKGAMMON	:= 0x92E;

// Backgammon Pieces
//--
const GID_WHITECHECKER	:= 0x91B;
const GID_BLACKCHECKER	:= 0x922;

// Chess Pieces
//--
const GID_WHITEBISHOP	:= 0x91C;
const GID_WHITEROOK	:= 0x91D;
const GID_WHITEKING	:= 0x91E;
const GID_WHITEKNIGHT	:= 0x91F;
const GID_WHITEPAWN	:= 0x920;
const GID_WHITEQUEEN	:= 0x921;
//--
const GID_BLACKBISHOP	:= 0x923;
const GID_BLACKROOK	:= 0x924;
const GID_BLACKKING	:= 0x925;
const GID_BLACKKNIGHT	:= 0x926;
const GID_BLACKPAWN	:= 0x927;
const GID_BLACKQUEEN	:= 0x928;
//--